# Generated by Django 4.0.2 on 2022-03-24 12:40

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=255)),
                ('arrangør', models.CharField(default='', max_length=40)),
                ('arrangør_username', models.CharField(default='', max_length=50)),
                ('dato', models.DateTimeField(null=True, validators=[events.models.validate_date])),
                ('beskrivelse', models.TextField(default='')),
                ('vanskelighetsgrad', models.CharField(choices=[('Enkel', 'Enkel'), ('Middels', 'Middels'), ('Krevende', 'Krevende'), ('Ekstra Krevende', 'Ekstra Krevende')], default='Enkel', max_length=15)),
                ('terreng', models.CharField(default='', max_length=40, null=True)),
                ('lengde', models.IntegerField(default=None, null=True)),
                ('utstyr', models.CharField(default='', max_length=40, null=True)),
                ('bilde', models.ImageField(blank=True, upload_to='static/uploads/')),
                ('synlig', models.BooleanField(default=True)),
                ('seriøsaktør', models.BooleanField(default=False)),
                ('pris', models.IntegerField(default=0)),
                ('destinasjon', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
