# Generated by Django 4.0.2 on 2022-02-22 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=255)),
                ('dato', models.DateField()),
                ('beskrivelse', models.TextField(default='')),
                ('bilde', models.ImageField(blank=True, upload_to='static/uploads/')),
                ('synlig', models.BooleanField(default=True)),
                ('arrangør', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
