# Generated by Django 4.0.2 on 2022-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrangør',
            field=models.CharField(default='', max_length=40),
        ),
    ]
