# Generated by Django 4.0.2 on 2022-02-24 14:44

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrangør',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='bilde',
            field=models.ImageField(blank=True, upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dato',
            field=models.DateField(null=True, validators=[events.models.validate_date]),
        ),
    ]
