# Generated by Django 4.0.2 on 2022-03-15 14:12

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_arrangør_event_bilde_alter_event_dato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dato',
            field=models.DateTimeField(null=True, validators=[events.models.validate_date]),
        ),
    ]
