# Generated by Django 4.0.2 on 2022-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_arrangør_event_bilde_alter_event_dato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bilde',
            field=models.ImageField(blank=True, upload_to='static/uploads/eventimages/'),
        ),
    ]
