# Generated by Django 4.0.2 on 2022-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='dato',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='tittel',
        ),
        migrations.AddField(
            model_name='event',
            name='beskrivelse',
            field=models.TextField(default='Beskrivelse'),
        ),
        migrations.AddField(
            model_name='event',
            name='bilde',
            field=models.ImageField(blank=True, upload_to='static/uploads/'),
        ),
    ]
