# Generated by Django 4.0.2 on 2022-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pris',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='seriøsaktør',
            field=models.BooleanField(default=False),
        ),
    ]
