# Generated by Django 4.0.2 on 2022-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
