# Generated by Django 4.0.2 on 2022-03-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_bilde'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='myapp_image',
        ),
    ]
