# Generated by Django 4.0.2 on 2022-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lengde',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='event',
            name='terreng',
            field=models.CharField(default='13', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='vanskelighetsgrad',
            field=models.CharField(choices=[('E', 'Enkel'), ('M', 'Middels'), ('K', 'Krevende'), ('EK', 'Ekstra Krevende')], default='E', max_length=2),
        ),
    ]
