# Generated by Django 4.0.2 on 2022-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_date_event_dato_rename_title_event_tittel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beskrivelse',
            field=models.TextField(default=''),
        ),
    ]
