# Generated by Django 4.0.2 on 2022-02-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_event_beskrivelse'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bruker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='synlig',
            field=models.BooleanField(default=True),
        ),
    ]
