# Generated by Django 4.0.2 on 2022-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_pris_event_seriøsaktør'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='adresse',
            field=models.CharField(default='', max_length=50),
        ),
    ]
