# Generated by Django 4.0.2 on 2022-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_lengde_event_terreng_event_vanskelighetsgrad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='terreng',
            field=models.CharField(default='skog', max_length=40),
        ),
    ]
