# Generated by Django 4.0.2 on 2022-03-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
