# Generated by Django 4.0.2 on 2022-02-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_bruker_event_synlig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bruker',
            new_name='arrangør',
        ),
    ]
