# Generated by Django 4.0.2 on 2022-03-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adresse',
        ),
    ]
