# Generated by Django 4.0.2 on 2022-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_terreng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='terreng',
            field=models.CharField(default='', max_length=40),
        ),
    ]
