# Generated by Django 4.0.2 on 2022-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrangør_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
