# Generated by Django 4.0.1 on 2022-02-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_arrangør'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='arrangør',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bilde',
        ),
    ]
