# Generated by Django 4.0.2 on 2022-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_arrangør_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='destinasjon',
            field=models.CharField(default='', max_length=80),
        ),
    ]
