# Generated by Django 4.0.2 on 2022-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_lengde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lengde',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='terreng',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
