# Generated by Django 4.0.2 on 2022-03-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_lengde_alter_event_terreng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='vanskelighetsgrad',
            field=models.CharField(choices=[('Enkel', 'Enkel'), ('Middels', 'Middels'), ('Krevende', 'Krevende'), ('Ekstra Krevende', 'Ekstra Krevende')], default='Enkel', max_length=15),
        ),
    ]
