# Generated by Django 4.0.2 on 2022-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_vanskelighetsgrad'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='utstyr',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lengde',
            field=models.IntegerField(default='', null=True),
        ),
    ]
