# Generated by Django 4.0.2 on 2022-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_utstyr_alter_event_lengde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lengde',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
