# Generated by Django 4.0.2 on 2022-03-17 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_arrangør_event_bilde_alter_event_dato'),
        ('brukere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turgåere',
            name='seriøsaktør',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turgåere',
            name='by',
            field=models.CharField(choices=[('trondheim', 'Trondheim'), ('bergen', 'Bergen'), ('oslo', 'Oslo'), ('tromsø', 'Tromsø')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='turgåere',
            name='ferdighetsnivå',
            field=models.CharField(choices=[('nybegynner', 'Nybegynner'), ('erfaren', 'Erfaren'), ('ekspert', 'Ekspert')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='turgåere',
            name='fødselsdato',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fødselsdato'),
        ),
        migrations.AlterField(
            model_name='turgåere',
            name='profilbilde',
            field=models.ImageField(default='placeholder.jpg', upload_to='static/uploads/profilbilder/'),
        ),
        migrations.CreateModel(
            name='User_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
