# Generated by Django 4.0.2 on 2022-02-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0002_remove_turgåere_fødselsdato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turgåere',
            name='by',
            field=models.CharField(choices=[('trondheim', 'Trondheim'), ('bergen', 'Bergen'), ('oslo', 'Oslo'), ('tromsø', 'Tromsø')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='turgåere',
            name='ferdighetsnivå',
            field=models.CharField(choices=[('nybegynner', 'Nybegynner'), ('erfaren', 'Erfaren'), ('ekspert', 'Ekspert')], default=' ', max_length=20),
        ),
    ]
