# Generated by Django 4.0.2 on 2022-02-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0003_alter_turgåere_by_alter_turgåere_ferdighetsnivå'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turgåere',
            name='profilbilde',
            field=models.ImageField(default='placeholder.jpg', upload_to='static/uploads/profilbilder/'),
        ),
    ]
