# Generated by Django 4.0.2 on 2022-03-15 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0005_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='turgåere',
            name='fødselsdato',
            field=models.DateField(default=datetime.date(2022, 3, 15), verbose_name='Fødselsdato'),
        ),
    ]
