# Generated by Django 4.0.2 on 2022-03-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0005_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='turgåere',
            name='seriøsaktør',
            field=models.BooleanField(default=False),
        ),
    ]
