# Generated by Django 4.0.2 on 2022-03-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0006_turgåere_seriøsaktør'),
        ('brukere', '0007_alter_turgåere_fødselsdato'),
    ]

    operations = [
    ]
