# Generated by Django 4.0.2 on 2022-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0007_alter_turgåere_fødselsdato'),
    ]

    operations = [
        migrations.AddField(
            model_name='turgåere',
            name='seriøsaktør',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turgåere',
            name='fødselsdato',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fødselsdato'),
        ),
    ]
