<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-17 12:35
=======
# Generated by Django 4.0.2 on 2022-03-17 13:44
>>>>>>> 27-12-som-bruker-onsker-jeg-a-soke-pa-turarrangement-og-sortere-dem-i-onsket-rekkefolge-slik-at-jeg

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('brukere', '0008_merge_20220317_1335'),
=======
        ('brukere', '0008_merge_20220317_1443'),
>>>>>>> 27-12-som-bruker-onsker-jeg-a-soke-pa-turarrangement-og-sortere-dem-i-onsket-rekkefolge-slik-at-jeg
    ]

    operations = [
        migrations.AlterField(
            model_name='turgåere',
            name='fødselsdato',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fødselsdato'),
        ),
    ]
