# Generated by Django 4.0.2 on 2022-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0008_merge_20220317_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turgåere',
            name='fødselsdato',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fødselsdato'),
        ),
    ]
