# Generated by Django 4.0.2 on 2022-03-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0008_merge_20220317_1335'),
        ('brukere', '0009_alter_turgåere_fødselsdato'),
    ]

    operations = [
    ]
