# Generated by Django 4.0.2 on 2022-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brukere', '0009_turgåere_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turgåere',
            old_name='adresse',
            new_name='bedriftsaddresse',
        ),
    ]
