# Generated by Django 4.0.2 on 2022-03-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_points'),
        ('brukere', '0009_alter_turgåere_fødselsdato'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvotePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('event_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
